-- 1. Create Tables

-- 1.1
CREATE TABLE Company
(IdCompany INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(150) UNIQUE,
Address VARCHAR(100))
-- 1.2
CREATE TABLE Status
(IdStatus INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(50))
-- 1.3
CREATE TABLE Projects
(IdProject INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Name VARCHAR(150) UNIQUE,
StartDate VARCHAR(10),
DeadLine VARCHAR(10),
FinishedOn VARCHAR(10),
StatusId INT)
-- 1.4
CREATE TABLE Employees
(IdEmployee INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FirstName VARCHAR(50),
LastName VARCHAR(50),
Email VARCHAR(100) UNIQUE,
Phone VARCHAR(12) UNIQUE,
Salary DECIMAL)

DROP TABLE Employees
DROP TABLE Projects
DROP TABLE Company
DROP TABLE Status

DROP DATABASE [practica-sql]